/**
 * Pre-computed Z3 verification results for the verify_demo modules.
 * Generated by: ailang verify --json verify_demo/<module>.ail
 *
 * Z3 is a compile-time tool (~40MB native binary) — it can't run in WASM.
 * These results are captured at build time and displayed in the browser.
 * The AILANG source is embedded so the WASM REPL can load and execute
 * the functions live for runtime demonstration.
 */

// ── Module metadata + contract descriptions ──────────────────

export const MODULES = {
  verify_showcase: {
    id: "verify_showcase",
    module: "verify_demo/verify_showcase",
    title: "Arithmetic",
    subtitle: "Pure integer functions",
    description: "Basic contracts on clamping, tax, safe subtraction, and tier discounts. Z3 proves bounds hold for all valid inputs.",
    icon: "calc",
    stats: { verified: 8, counterexample: 3, skipped: 0 },
    functions: {
      clampPrice: {
        signature: "clampPrice(price: int, min: int, max: int) -> int",
        requires: "min >= 0, max >= min",
        ensures: "result >= min, result <= max",
        description: "Clamp a price to [min, max] range",
        tryIt: { params: [
          { name: "price", type: "int", default: 250 },
          { name: "min", type: "int", default: 100 },
          { name: "max", type: "int", default: 500 }
        ]}
      },
      applyTax: {
        signature: "applyTax(amount: int, rateBps: int) -> int",
        requires: "amount >= 0, rateBps >= 0",
        ensures: "result >= amount",
        description: "Apply tax in basis points (500 bps = 5%)",
        tryIt: { params: [
          { name: "amount", type: "int", default: 10000 },
          { name: "rateBps", type: "int", default: 500 }
        ]}
      },
      safeSubtract: {
        signature: "safeSubtract(a: int, b: int) -> int",
        requires: "a >= 0, b >= 0",
        ensures: "result >= 0",
        description: "Subtraction that floors at zero",
        tryIt: { params: [
          { name: "a", type: "int", default: 3 },
          { name: "b", type: "int", default: 10 }
        ]}
      },
      tierDiscount: {
        signature: "tierDiscount(qty: int) -> int",
        requires: "qty >= 0",
        ensures: "result >= 0, result <= 30",
        description: "Classify quantity into discount tier",
        tryIt: { params: [
          { name: "qty", type: "int", default: 150 }
        ]}
      },
      validateAge: {
        signature: "validateAge(age: int) -> int",
        requires: "age >= 0, age <= 150",
        ensures: "result >= 0, result <= 150",
        description: "Validate age is in accepted range",
        tryIt: { params: [
          { name: "age", type: "int", default: 25 }
        ]}
      },
      calculateIncomeTax: {
        signature: "calculateIncomeTax(income: int, bracketPct: int) -> int",
        requires: "income >= 0, bracketPct >= 0, bracketPct <= 50",
        ensures: "result >= 0",
        description: "Tax bracket calculation",
        tryIt: { params: [
          { name: "income", type: "int", default: 50000 },
          { name: "bracketPct", type: "int", default: 22 }
        ]}
      },
      priceDifference: {
        signature: "priceDifference(a: int, b: int) -> int",
        requires: null,
        ensures: "result >= 0",
        description: "Absolute difference between two prices",
        tryIt: { params: [
          { name: "a", type: "int", default: 100 },
          { name: "b", type: "int", default: 250 }
        ]}
      },
      brokenDiscount: {
        signature: "brokenDiscount(price: int, discount: int) -> int",
        requires: "price >= 0, discount >= 0",
        ensures: "result >= 0",
        description: "BUGGY: discount can exceed price",
        bug: "When discount > price, result goes negative. Z3 finds: price=0, discount=1 -> result=-1",
        tryIt: { params: [
          { name: "price", type: "int", default: 0 },
          { name: "discount", type: "int", default: 1 }
        ]}
      },
      splitBill: {
        signature: "splitBill(total: int, people: int) -> int",
        requires: "total >= 0, people >= 1",
        ensures: "result * people <= total",
        description: "BUGGY: ceiling division overshoots",
        bug: "Rounds up to prevent underpayment, but rounding up means result * people exceeds total. Z3 finds: total=1, people=2 → ceil(1/2)=1, but 1×2=2 > 1",
        tryIt: { params: [
          { name: "total", type: "int", default: 1 },
          { name: "people", type: "int", default: 2 }
        ]}
      },
      clampPositive: {
        signature: "clampPositive(x: int) -> int",
        requires: null,
        ensures: "result > 0",
        description: "BUGGY: off-by-one — zero is not positive",
        bug: "Claims result is strictly positive, but clamping negative values to 0 violates > 0. Z3 finds: x=0 → result=0, but 0 is not > 0",
        tryIt: { params: [
          { name: "x", type: "int", default: 0 }
        ]}
      },
      factorial: {
        signature: "factorial(n: int) -> int",
        requires: "n >= 0, n <= 10",
        ensures: "result >= 1",
        description: "Recursive — verified via bounded unrolling (depth 10)",
        boundedDepth: 10,
        tryIt: { params: [
          { name: "n", type: "int", default: 5 }
        ]}
      }
    }
  },

  billing: {
    id: "billing",
    module: "verify_demo/billing",
    title: "Cloud Billing",
    subtitle: "Enums, records, strings, lists",
    description: "Full billing pipeline: usage metering, tier discounts, regional tax, promo rebates. 4-deep cross-function chain with Z3 string and sequence theory.",
    icon: "billing",
    stats: { verified: 12, counterexample: 2, skipped: 0 },
    functions: {
      taxRate: {
        signature: "taxRate(region: Region) -> int",
        requires: null,
        ensures: "result >= 0, result <= 2300",
        description: "Regional tax rate in basis points",
        tryIt: { params: [
          { name: "region", type: "enum", options: ["US_EAST", "EU_WEST", "APAC", "LATAM"], default: "EU_WEST" }
        ]}
      },
      computeTax: {
        signature: "computeTax(amount: int, region: Region) -> int",
        requires: "amount >= 0",
        ensures: "result >= 0",
        description: "Compute tax on an amount (cross-function)",
        tryIt: { params: [
          { name: "amount", type: "int", default: 10000 },
          { name: "region", type: "enum", options: ["US_EAST", "EU_WEST", "APAC", "LATAM"], default: "US_EAST" }
        ]}
      },
      unitPrice: {
        signature: "unitPrice(tier: CustomerTier) -> int",
        requires: null,
        ensures: "result >= 10",
        description: "Per-unit price by tier",
        tryIt: { params: [
          { name: "tier", type: "enum", options: ["ENTERPRISE", "BUSINESS", "STARTUP", "FREE"], default: "ENTERPRISE" }
        ]}
      },
      tierDiscountBps: {
        signature: "tierDiscountBps(tier: CustomerTier) -> int",
        requires: null,
        ensures: "result >= 0, result <= 3000",
        description: "Tier discount rate in basis points",
        tryIt: { params: [
          { name: "tier", type: "enum", options: ["ENTERPRISE", "BUSINESS", "STARTUP", "FREE"], default: "ENTERPRISE" }
        ]}
      },
      applyTierDiscount: {
        signature: "applyTierDiscount(amount: int, tier: CustomerTier) -> int",
        requires: "amount >= 0",
        ensures: "result >= 0, result <= amount",
        description: "Apply tier discount (cross-function)",
        tryIt: { params: [
          { name: "amount", type: "int", default: 10000 },
          { name: "tier", type: "enum", options: ["ENTERPRISE", "BUSINESS", "STARTUP", "FREE"], default: "BUSINESS" }
        ]}
      },
      usageCost: {
        signature: "usageCost(units: int, tier: CustomerTier) -> int",
        requires: "units >= 0",
        ensures: "result >= 0",
        description: "Raw usage cost (cross-function)",
        tryIt: { params: [
          { name: "units", type: "int", default: 500 },
          { name: "tier", type: "enum", options: ["ENTERPRISE", "BUSINESS", "STARTUP", "FREE"], default: "STARTUP" }
        ]}
      },
      isValidPromo: {
        signature: "isValidPromo(code: string) -> bool",
        requires: null,
        ensures: 'result == (startsWith(code, "CLOUD-") && len(code) >= 10)',
        description: "Z3 string theory: promo code validation",
        tryIt: { params: [
          { name: "code", type: "string", default: "CLOUD-LAUNCH2024" }
        ]}
      },
      promoRebate: {
        signature: "promoRebate(code: string, amount: int) -> int",
        requires: "amount >= 0",
        ensures: "result >= 0, result <= amount",
        description: "15% rebate if valid promo code",
        tryIt: { params: [
          { name: "code", type: "string", default: "CLOUD-LAUNCH2024" },
          { name: "amount", type: "int", default: 10000 }
        ]}
      },
      lineItemCount: {
        signature: "lineItemCount(items: [int]) -> int",
        requires: null,
        ensures: "result >= 0",
        description: "Z3 sequence theory: list length",
        noTryIt: "Takes a list parameter — not supported in browser demo"
      },
      addLineItem: {
        signature: "addLineItem(cost: int, items: [int]) -> int",
        requires: null,
        ensures: "result == length(items) + 1",
        description: "Z3 proves: cons increases length by 1",
        noTryIt: "Takes a list parameter — not supported in browser demo"
      },
      netFromBill: {
        signature: "netFromBill(bill: {subtotal, tax, discount, credits}) -> int",
        requires: "bill.subtotal >= 0, bill.tax >= 0, bill.discount >= 0, bill.credits >= 0, bill.discount <= bill.subtotal",
        ensures: "result >= 0",
        description: "Record contracts: net from bill summary",
        noTryIt: "Takes a record parameter — not supported in browser demo"
      },
      finalBill: {
        signature: "finalBill(units: int, tier: CustomerTier, region: Region, promoCode: string) -> int",
        requires: "units >= 0",
        ensures: "result >= 0",
        description: "4-deep cross-function chain: the full pipeline",
        tryIt: { params: [
          { name: "units", type: "int", default: 1000 },
          { name: "tier", type: "enum", options: ["ENTERPRISE", "BUSINESS", "STARTUP", "FREE"], default: "ENTERPRISE" },
          { name: "region", type: "enum", options: ["US_EAST", "EU_WEST", "APAC", "LATAM"], default: "EU_WEST" },
          { name: "promoCode", type: "string", default: "CLOUD-LAUNCH2024" }
        ]}
      },
      brokenCreditApply: {
        signature: "brokenCreditApply(subtotal: int, credits: int) -> int",
        requires: "subtotal >= 0, credits >= 0",
        ensures: "result >= 0",
        description: "BUGGY: credits can exceed subtotal",
        bug: "Large referral credits ($100) on a small plan ($5) goes negative. Z3 finds: subtotal=0, credits=1 -> result=-1",
        tryIt: { params: [
          { name: "subtotal", type: "int", default: 0 },
          { name: "credits", type: "int", default: 1 }
        ]}
      },
      proratedRefund: {
        signature: "proratedRefund(price: int, daysUsed: int, warrantyDays: int) -> int",
        requires: "price >= 0, daysUsed >= 0, warrantyDays >= 1",
        ensures: "result >= 0",
        description: "BUGGY: refund goes negative past warranty",
        bug: "Prorated refund = price × (warranty - daysUsed) / warranty. After warranty expires, numerator goes negative. Z3 finds: price=1, daysUsed=3, warrantyDays=1 → 1×(1-3)/1 = -2",
        tryIt: { params: [
          { name: "price", type: "int", default: 100 },
          { name: "daysUsed", type: "int", default: 400 },
          { name: "warrantyDays", type: "int", default: 365 }
        ]}
      }
    }
  },

  access_policy: {
    id: "access_policy",
    module: "verify_demo/access_policy",
    title: "Access Control",
    subtitle: "Security invariants",
    description: "Role-based access control: 4 roles x 4 resources x 3 actions = 48 permission paths. Z3 proves admin supremacy, guest isolation, and role monotonicity.",
    icon: "shield",
    stats: { verified: 10, counterexample: 2, skipped: 0 },
    functions: {
      roleWeight: {
        signature: "roleWeight(role: Role) -> int",
        requires: null,
        ensures: "result >= 0, result <= 100",
        description: "Base permission score for a role",
        tryIt: { params: [
          { name: "role", type: "enum", options: ["ADMIN", "EDITOR", "VIEWER", "GUEST"], default: "ADMIN" }
        ]}
      },
      actionThreshold: {
        signature: "actionThreshold(action: Action) -> int",
        requires: null,
        ensures: "result >= 10, result <= 80",
        description: "Minimum level required for an action",
        tryIt: { params: [
          { name: "action", type: "enum", options: ["READ", "WRITE", "DELETE"], default: "WRITE" }
        ]}
      },
      resourceSensitivity: {
        signature: "resourceSensitivity(resource: Resource) -> int",
        requires: null,
        ensures: "result >= 0, result <= 20",
        description: "Resource sensitivity modifier",
        tryIt: { params: [
          { name: "resource", type: "enum", options: ["DOCUMENTS", "SETTINGS", "AUDIT_LOG", "USER_DATA"], default: "SETTINGS" }
        ]}
      },
      isAllowed: {
        signature: "isAllowed(role: Role, resource: Resource, action: Action) -> bool",
        requires: null,
        ensures: null,
        description: "Combined permission check (3-way cross-function)",
        tryIt: { params: [
          { name: "role", type: "enum", options: ["ADMIN", "EDITOR", "VIEWER", "GUEST"], default: "ADMIN" },
          { name: "resource", type: "enum", options: ["DOCUMENTS", "SETTINGS", "AUDIT_LOG", "USER_DATA"], default: "AUDIT_LOG" },
          { name: "action", type: "enum", options: ["READ", "WRITE", "DELETE"], default: "DELETE" }
        ]}
      },
      adminAlwaysAllowed: {
        signature: "adminAlwaysAllowed(resource: Resource, action: Action) -> bool",
        requires: null,
        ensures: "result == true",
        description: "ADMIN SUPREMACY: admins can always do anything",
        tryIt: { params: [
          { name: "resource", type: "enum", options: ["DOCUMENTS", "SETTINGS", "AUDIT_LOG", "USER_DATA"], default: "AUDIT_LOG" },
          { name: "action", type: "enum", options: ["READ", "WRITE", "DELETE"], default: "DELETE" }
        ]}
      },
      guestCannotWrite: {
        signature: "guestCannotWrite(resource: Resource) -> bool",
        requires: null,
        ensures: "result == true",
        description: "GUEST ISOLATION: guests can never write",
        tryIt: { params: [
          { name: "resource", type: "enum", options: ["DOCUMENTS", "SETTINGS", "AUDIT_LOG", "USER_DATA"], default: "SETTINGS" }
        ]}
      },
      guestCannotDelete: {
        signature: "guestCannotDelete(resource: Resource) -> bool",
        requires: null,
        ensures: "result == true",
        description: "GUEST ISOLATION: guests can never delete",
        tryIt: { params: [
          { name: "resource", type: "enum", options: ["DOCUMENTS", "SETTINGS", "AUDIT_LOG", "USER_DATA"], default: "USER_DATA" }
        ]}
      },
      viewerCannotWriteSensitive: {
        signature: "viewerCannotWriteSensitive(resource: Resource) -> bool",
        requires: null,
        ensures: "result == true",
        description: "VIEWER RESTRICTION: can't write sensitive resources",
        tryIt: { params: [
          { name: "resource", type: "enum", options: ["DOCUMENTS", "SETTINGS", "AUDIT_LOG", "USER_DATA"], default: "SETTINGS" }
        ]}
      },
      adminOutranksEditor: {
        signature: "adminOutranksEditor(resource: Resource, action: Action) -> bool",
        requires: null,
        ensures: "result == true",
        description: "MONOTONICITY: admin >= editor for all ops",
        tryIt: { params: [
          { name: "resource", type: "enum", options: ["DOCUMENTS", "SETTINGS", "AUDIT_LOG", "USER_DATA"], default: "DOCUMENTS" },
          { name: "action", type: "enum", options: ["READ", "WRITE", "DELETE"], default: "WRITE" }
        ]}
      },
      editorOutranksViewer: {
        signature: "editorOutranksViewer(resource: Resource, action: Action) -> bool",
        requires: null,
        ensures: "result == true",
        description: "MONOTONICITY: editor >= viewer for all ops",
        tryIt: { params: [
          { name: "resource", type: "enum", options: ["DOCUMENTS", "SETTINGS", "AUDIT_LOG", "USER_DATA"], default: "DOCUMENTS" },
          { name: "action", type: "enum", options: ["READ", "WRITE", "DELETE"], default: "DELETE" }
        ]}
      },
      auditRiskScore: {
        signature: "auditRiskScore(role: Role, action: Action, resource: Resource) -> int",
        requires: null,
        ensures: "result >= 0, result <= 200",
        description: "Risk score for action attempt",
        tryIt: { params: [
          { name: "role", type: "enum", options: ["ADMIN", "EDITOR", "VIEWER", "GUEST"], default: "GUEST" },
          { name: "action", type: "enum", options: ["READ", "WRITE", "DELETE"], default: "DELETE" },
          { name: "resource", type: "enum", options: ["DOCUMENTS", "SETTINGS", "AUDIT_LOG", "USER_DATA"], default: "USER_DATA" }
        ]}
      },
      brokenEscalationCheck: {
        signature: "brokenEscalationCheck(role: Role, action: Action) -> int",
        requires: null,
        ensures: "result <= roleWeight(role)",
        description: "BUGGY: read bonus pushes level above role weight",
        bug: "READ bonus (+15) minus READ threshold (-10) = net +5 pushes EDITOR from 60 to 65, exceeding roleWeight(EDITOR)=60. Z3 finds: role=EDITOR, action=READ",
        tryIt: { params: [
          { name: "role", type: "enum", options: ["ADMIN", "EDITOR", "VIEWER", "GUEST"], default: "EDITOR" },
          { name: "action", type: "enum", options: ["READ", "WRITE", "DELETE"], default: "READ" }
        ]}
      },
      upgradeGain: {
        signature: "upgradeGain(fromRole: Role, toRole: Role, resource: Resource) -> int",
        requires: "roleWeight(toRole) >= roleWeight(fromRole)",
        ensures: "result >= 0",
        description: "BUGGY: sensitivity eats the upgrade benefit",
        bug: "Subtracts resource sensitivity as 'security buffer', but when both roles are the same, the weight diff is 0 and sensitivity makes it negative. Z3 finds: fromRole=GUEST, toRole=GUEST, resource=SETTINGS → 10-10-15 = -15",
        tryIt: { params: [
          { name: "fromRole", type: "enum", options: ["ADMIN", "EDITOR", "VIEWER", "GUEST"], default: "GUEST" },
          { name: "toRole", type: "enum", options: ["ADMIN", "EDITOR", "VIEWER", "GUEST"], default: "GUEST" },
          { name: "resource", type: "enum", options: ["DOCUMENTS", "SETTINGS", "AUDIT_LOG", "USER_DATA"], default: "SETTINGS" }
        ]}
      }
    }
  },

  scheduling: {
    id: "scheduling",
    module: "verify_demo/scheduling",
    title: "Scheduling",
    subtitle: "Capacity & priority",
    description: "Conference room booking: 3 rooms x 4 priorities x 4 time slots. Z3 proves capacity bounds, priority ordering (VIP > HIGH > STANDARD > LOW), and cost positivity.",
    icon: "calendar",
    stats: { verified: 13, counterexample: 2, skipped: 0 },
    functions: {
      roomCapacity: {
        signature: "roomCapacity(room: RoomType) -> int",
        requires: null,
        ensures: "result >= 4, result <= 200",
        description: "Maximum occupancy per room type",
        tryIt: { params: [
          { name: "room", type: "enum", options: ["SMALL", "MEDIUM", "LARGE"], default: "MEDIUM" }
        ]}
      },
      fitsInRoom: {
        signature: "fitsInRoom(headcount: int, room: RoomType) -> bool",
        requires: "headcount >= 1",
        ensures: "result == (headcount <= roomCapacity(room))",
        description: "Check if booking fits (cross-function)",
        tryIt: { params: [
          { name: "headcount", type: "int", default: 15 },
          { name: "room", type: "enum", options: ["SMALL", "MEDIUM", "LARGE"], default: "SMALL" }
        ]}
      },
      remainingCapacity: {
        signature: "remainingCapacity(room: RoomType, currentOccupancy: int) -> int",
        requires: "currentOccupancy >= 0, currentOccupancy <= roomCapacity(room)",
        ensures: "result >= 0",
        description: "Remaining capacity after booking",
        tryIt: { params: [
          { name: "room", type: "enum", options: ["SMALL", "MEDIUM", "LARGE"], default: "LARGE" },
          { name: "currentOccupancy", type: "int", default: 50 }
        ]}
      },
      priorityWeight: {
        signature: "priorityWeight(priority: Priority) -> int",
        requires: null,
        ensures: "result >= 10, result <= 100",
        description: "Priority weight (higher = more important)",
        tryIt: { params: [
          { name: "priority", type: "enum", options: ["VIP", "HIGH", "STANDARD", "LOW"], default: "VIP" }
        ]}
      },
      slotDemand: {
        signature: "slotDemand(slot: TimeSlot) -> int",
        requires: null,
        ensures: "result >= 80, result <= 150",
        description: "Time slot demand multiplier (%)",
        tryIt: { params: [
          { name: "slot", type: "enum", options: ["MORNING", "MIDDAY", "AFTERNOON", "EVENING"], default: "MORNING" }
        ]}
      },
      bookingScore: {
        signature: "bookingScore(priority: Priority, slot: TimeSlot) -> int",
        requires: null,
        ensures: "result >= 800",
        description: "Combined score: priority x demand",
        tryIt: { params: [
          { name: "priority", type: "enum", options: ["VIP", "HIGH", "STANDARD", "LOW"], default: "VIP" },
          { name: "slot", type: "enum", options: ["MORNING", "MIDDAY", "AFTERNOON", "EVENING"], default: "MORNING" }
        ]}
      },
      vipOutranksHigh: {
        signature: "vipOutranksHigh(slot: TimeSlot) -> bool",
        requires: null,
        ensures: "result == true",
        description: "VIP SUPREMACY: VIP always outscores HIGH",
        tryIt: { params: [
          { name: "slot", type: "enum", options: ["MORNING", "MIDDAY", "AFTERNOON", "EVENING"], default: "EVENING" }
        ]}
      },
      highOutranksStandard: {
        signature: "highOutranksStandard(slot: TimeSlot) -> bool",
        requires: null,
        ensures: "result == true",
        description: "MONOTONICITY: HIGH always outscores STANDARD",
        tryIt: { params: [
          { name: "slot", type: "enum", options: ["MORNING", "MIDDAY", "AFTERNOON", "EVENING"], default: "MIDDAY" }
        ]}
      },
      standardOutranksLow: {
        signature: "standardOutranksLow(slot: TimeSlot) -> bool",
        requires: null,
        ensures: "result == true",
        description: "MONOTONICITY: STANDARD always outscores LOW",
        tryIt: { params: [
          { name: "slot", type: "enum", options: ["MORNING", "MIDDAY", "AFTERNOON", "EVENING"], default: "AFTERNOON" }
        ]}
      },
      baseRoomCost: {
        signature: "baseRoomCost(room: RoomType) -> int",
        requires: null,
        ensures: "result >= 500",
        description: "Base room cost per slot (cents)",
        tryIt: { params: [
          { name: "room", type: "enum", options: ["SMALL", "MEDIUM", "LARGE"], default: "LARGE" }
        ]}
      },
      capacitySurcharge: {
        signature: "capacitySurcharge(room: RoomType, headcount: int) -> int",
        requires: "headcount >= 1, headcount <= roomCapacity(room)",
        ensures: "result >= 0",
        description: "Extra cost above half capacity",
        tryIt: { params: [
          { name: "room", type: "enum", options: ["SMALL", "MEDIUM", "LARGE"], default: "MEDIUM" },
          { name: "headcount", type: "int", default: 15 }
        ]}
      },
      priorityPremium: {
        signature: "priorityPremium(priority: Priority) -> int",
        requires: null,
        ensures: "result >= 0, result <= 50",
        description: "Priority premium percentage",
        tryIt: { params: [
          { name: "priority", type: "enum", options: ["VIP", "HIGH", "STANDARD", "LOW"], default: "HIGH" }
        ]}
      },
      totalBookingCost: {
        signature: "totalBookingCost(room: RoomType, headcount: int, priority: Priority, slot: TimeSlot) -> int",
        requires: "headcount >= 1, headcount <= roomCapacity(room)",
        ensures: "result >= 0",
        description: "Full booking cost: 4-deep chain",
        tryIt: { params: [
          { name: "room", type: "enum", options: ["SMALL", "MEDIUM", "LARGE"], default: "MEDIUM" },
          { name: "headcount", type: "int", default: 15 },
          { name: "priority", type: "enum", options: ["VIP", "HIGH", "STANDARD", "LOW"], default: "HIGH" },
          { name: "slot", type: "enum", options: ["MORNING", "MIDDAY", "AFTERNOON", "EVENING"], default: "MIDDAY" }
        ]}
      },
      brokenDoubleBook: {
        signature: "brokenDoubleBook(room: RoomType, headcountA: int, headcountB: int) -> bool",
        requires: "headcountA >= 1, headcountB >= 1",
        ensures: "result == (headcountA + headcountB <= roomCapacity(room))",
        description: "BUGGY: off-by-one allows overbooking",
        bug: "Developer added +1 thinking 'inclusive' — this disagrees with the contract. Z3 finds: room=SMALL, headcountA=1, headcountB=3 (capacity=4, but 1+3+1=5 > 4)",
        tryIt: { params: [
          { name: "room", type: "enum", options: ["SMALL", "MEDIUM", "LARGE"], default: "SMALL" },
          { name: "headcountA", type: "int", default: 1 },
          { name: "headcountB", type: "int", default: 3 }
        ]}
      },
      overtimeCost: {
        signature: "overtimeCost(baseRate: int, overtimeHours: int) -> int",
        requires: "baseRate >= 0, overtimeHours >= 0",
        ensures: "result >= 0",
        description: "BUGGY: flat fee waiver makes cost negative",
        bug: "1.5x overtime premium minus 50-cent 'loyalty waiver' looks harmless, but with zero base and zero overtime the waiver alone makes it -50. Z3 finds: baseRate=0, overtimeHours=0 → 0+0-50 = -50",
        tryIt: { params: [
          { name: "baseRate", type: "int", default: 0 },
          { name: "overtimeHours", type: "int", default: 0 }
        ]}
      }
    }
  }
};

// ── Pre-computed Z3 verification results ────────────────────
// Raw output from `ailang verify --json verify_demo/<module>.ail`

export const VERIFY_RESULTS = {
  verify_showcase: {
    file: "verify_demo/verify_showcase.ail",
    verified: 8, counterexample: 3, skipped: 0, errors: 0,
    results: [
      { function: "clampPrice", status: "verified" },
      { function: "applyTax", status: "verified" },
      { function: "safeSubtract", status: "verified" },
      { function: "tierDiscount", status: "verified" },
      { function: "validateAge", status: "verified" },
      { function: "calculateIncomeTax", status: "verified" },
      { function: "priceDifference", status: "verified" },
      { function: "brokenDiscount", status: "counterexample",
        model: [
          { name: "price", sort: "Int", value: "0" },
          { name: "discount", sort: "Int", value: "1" }
        ]},
      { function: "splitBill", status: "counterexample",
        model: [
          { name: "total", sort: "Int", value: "1" },
          { name: "people", sort: "Int", value: "2" }
        ]},
      { function: "clampPositive", status: "counterexample",
        model: [
          { name: "x", sort: "Int", value: "0" }
        ]},
      { function: "factorial", status: "verified",
        bounded_depth: 10 }
    ]
  },

  billing: {
    file: "verify_demo/billing.ail",
    verified: 12, counterexample: 2, skipped: 0, errors: 0,
    results: [
      { function: "taxRate", status: "verified" },
      { function: "computeTax", status: "verified" },
      { function: "unitPrice", status: "verified" },
      { function: "tierDiscountBps", status: "verified" },
      { function: "applyTierDiscount", status: "verified" },
      { function: "usageCost", status: "verified" },
      { function: "isValidPromo", status: "verified" },
      { function: "promoRebate", status: "verified" },
      { function: "lineItemCount", status: "verified" },
      { function: "addLineItem", status: "verified" },
      { function: "netFromBill", status: "verified" },
      { function: "finalBill", status: "verified" },
      { function: "brokenCreditApply", status: "counterexample",
        model: [
          { name: "subtotal", sort: "Int", value: "0" },
          { name: "credits", sort: "Int", value: "1" }
        ]},
      { function: "proratedRefund", status: "counterexample",
        model: [
          { name: "price", sort: "Int", value: "1" },
          { name: "daysUsed", sort: "Int", value: "3" },
          { name: "warrantyDays", sort: "Int", value: "1" }
        ]}
    ]
  },

  access_policy: {
    file: "verify_demo/access_policy.ail",
    verified: 10, counterexample: 2, skipped: 0, errors: 0,
    results: [
      { function: "roleWeight", status: "verified" },
      { function: "actionThreshold", status: "verified" },
      { function: "resourceSensitivity", status: "verified" },
      { function: "isAllowed", status: "verified" },
      { function: "adminAlwaysAllowed", status: "verified" },
      { function: "guestCannotWrite", status: "verified" },
      { function: "guestCannotDelete", status: "verified" },
      { function: "viewerCannotWriteSensitive", status: "verified" },
      { function: "adminOutranksEditor", status: "verified" },
      { function: "editorOutranksViewer", status: "verified" },
      { function: "auditRiskScore", status: "verified" },
      { function: "brokenEscalationCheck", status: "counterexample",
        model: [
          { name: "role", sort: "Role", value: "EDITOR" },
          { name: "action", sort: "Action", value: "READ" }
        ]},
      { function: "upgradeGain", status: "counterexample",
        model: [
          { name: "fromRole", sort: "Role", value: "GUEST" },
          { name: "toRole", sort: "Role", value: "GUEST" },
          { name: "resource", sort: "Resource", value: "SETTINGS" }
        ]}
    ]
  },

  scheduling: {
    file: "verify_demo/scheduling.ail",
    verified: 13, counterexample: 2, skipped: 0, errors: 0,
    results: [
      { function: "roomCapacity", status: "verified" },
      { function: "fitsInRoom", status: "verified" },
      { function: "remainingCapacity", status: "verified" },
      { function: "priorityWeight", status: "verified" },
      { function: "slotDemand", status: "verified" },
      { function: "bookingScore", status: "verified" },
      { function: "vipOutranksHigh", status: "verified" },
      { function: "highOutranksStandard", status: "verified" },
      { function: "standardOutranksLow", status: "verified" },
      { function: "baseRoomCost", status: "verified" },
      { function: "capacitySurcharge", status: "verified" },
      { function: "priorityPremium", status: "verified" },
      { function: "totalBookingCost", status: "verified" },
      { function: "brokenDoubleBook", status: "counterexample",
        model: [
          { name: "room", sort: "RoomType", value: "SMALL" },
          { name: "headcountA", sort: "Int", value: "1" },
          { name: "headcountB", sort: "Int", value: "3" }
        ]},
      { function: "overtimeCost", status: "counterexample",
        model: [
          { name: "baseRate", sort: "Int", value: "0" },
          { name: "overtimeHours", sort: "Int", value: "0" }
        ]}
    ]
  }
};

// ── Display order for functions in each module ──────────────
// (logical grouping rather than Z3 output order)

export const DISPLAY_ORDER = {
  verify_showcase: [
    "clampPrice", "applyTax", "safeSubtract", "tierDiscount",
    "validateAge", "calculateIncomeTax", "priceDifference",
    "brokenDiscount", "splitBill", "clampPositive", "factorial"
  ],
  billing: [
    "taxRate", "computeTax", "unitPrice", "tierDiscountBps",
    "applyTierDiscount", "usageCost", "isValidPromo", "promoRebate",
    "lineItemCount", "addLineItem", "netFromBill", "finalBill",
    "brokenCreditApply", "proratedRefund"
  ],
  access_policy: [
    "roleWeight", "actionThreshold", "resourceSensitivity", "isAllowed",
    "adminAlwaysAllowed", "guestCannotWrite", "guestCannotDelete",
    "viewerCannotWriteSensitive", "adminOutranksEditor", "editorOutranksViewer",
    "auditRiskScore", "brokenEscalationCheck", "upgradeGain"
  ],
  scheduling: [
    "roomCapacity", "fitsInRoom", "remainingCapacity",
    "priorityWeight", "slotDemand", "bookingScore",
    "vipOutranksHigh", "highOutranksStandard", "standardOutranksLow",
    "baseRoomCost", "capacitySurcharge", "priorityPremium", "totalBookingCost",
    "brokenDoubleBook", "overtimeCost"
  ]
};
