export const scenarios = [
  { id: 'direct', name: 'Print the key', action: 'Send it straight to public output.', route: 'Direct transfer', expected: 'blocked', why: 'The input carries <secret>. publish refuses that label, so this call is rejected before execution.' },
  { id: 'url', name: 'Hide it in a URL', action: 'Put the key inside a harmless-looking link.', route: 'String interpolation', expected: 'blocked', why: 'Embedding a secret in a larger string does not remove its label. The whole URL carries the secret label.' },
  { id: 'helper', name: 'Use a helper', action: 'Pass the key through an ordinary formatting function.', route: 'Helper function', expected: 'blocked', why: 'A helper does not automatically create a trust boundary. The label propagates through this call.' },
  { id: 'record', name: 'Wrap it in a record', action: 'Package the key as a support message.', route: 'Record field', expected: 'blocked', why: 'Putting the value in a record and reading it back does not make it public.' },
  { id: 'relabel', name: 'Call it public', action: 'Change the return label without declaring authority.', route: 'Unapproved label change', expected: 'blocked', why: 'An explicit public return label cannot silently hide a secret. Lowering the label requires the Declassify effect.' },
  { id: 'redact', name: 'Release a redacted value', action: 'Declare a gate that replaces the input with a constant.', route: 'Explicit redaction gate', expected: 'allowed', why: 'This gate declares Declassify and returns only “[redacted]”. The IFC check permits the flow. Its body is visible for review.' },
  { id: 'authority', name: 'Abuse the authority', action: 'Declare Declassify, then return the original key.', route: 'Dangerous release gate', expected: 'allowed', why: 'The checker permits this because you explicitly granted declassification authority. Declassify is permission to lower a label, not proof of sanitisation. A gate needs review and, where supported, contracts.' },
];
